### ISSUE TITLE
Vehicle not starting when spawned.

### ISSUE THREAD

**Issue by MattiVboiii** [CritteRo/CritteR-s-Blood-Bowl#3]
Hello, I have a problem with the cars... The intro and everything works fine but when you are seated in the car in the beginning, it freezes and you can't accelerate. I've tried lockpicking it and that works. If there is anything I did wrong, please let me know. I can send proof too if that is neccasary. :)

**Comment by CritteRo** [comment]
" I've tried lockpicking it and that works. "

It's probably some script that you have, that stops the car engine, or prevents the player from starting the engine.

**Comment by MattiVboiii** [comment]
Do you have any idea how I could disable that for certain vehicles?
